spring.application.name= job-application-tracker
spring.config.import= optional:file:.env[.properties]
#----------------------------------------------------------------------------------#
#Database Connection Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
#----------------------------------------------------------------------------------#
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#----------------------------------------------------------------------------------#
Jwt.secret.key=${JWT_SECRET}
#----------------------------------------------------------------------------------#

# (1000*60*5)= 5 minutes
jwt.expiration.access-token=${JWT_ACCESS}
jwt.expiration.refresh-token=${JWT_REFRESHMENT_DAYS}