name: github workflow
on:
  push:
    branches:
      - "main"
jobs:
  first-workflow-job:
    name: first
    runs-on: ubuntu-latest
    steps:
      - name: run bash command
        run: echo "github workflow"
        shell: bash
